# For development

version: "3.4"

services:
  api:
    build:
      context: ./api
      target: dev
    volumes:
      - ./api:/go/src/api
    ports:
      - 8080:8080
    env_file:
      - ./api/.env.example
      - ./api/.env
  webapp:
    build:
      context: ./webapp
    volumes:
      - ./webapp/src:/usr/src/app/src
    ports:
      - 8000:8000
    env_file:
      - ./webapp/.env.example
      - ./webapp/.env
